# Copyright (c) 2021 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Boost the Bluetooth signal
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Allow reconnection without GATT subscription (fixes iOS)
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
